### ISSUE TITLE
Update json-path library

### ISSUE THREAD

**Issue by Sheldor5** [ATLANTBH/jmeter-components#11]
Can you please update the json-path library to 2.0.0? The current version (0.9.0) does not work for me if I want to filter by String values (see http://stackoverflow.com/questions/12585968/how-to-filter-by-string-in-jsonpath & http://stackoverflow.com/questions/32455219/jsonpath-get-all-values-where-object-othervalue-equals-string).

**Comment by tarikabh** [comment]
The library is now updated.
